Add room crud
eisen-oxid/thermit pull request #27
Opened 2021-03-19 15:30 UTC by frcroth

2021-03-28 18:02 UTC, sirkrypt0 requested changes

2021-03-28 18:02 UTC, sirkrypt0 commented on server/src/errors.rs
> +
Issue #30 applies here as well. Not sure what is missing tho.

2021-03-28 18:02 UTC, sirkrypt0 commented on server/src/room/routes.rs
> +    }
I found that `NoContent` is not good when an empty list is returned. https://stackoverflow.com/questions/13366730/proper-rest-response-for-empty-table

Furthermore I suggest returning a real json object and not only a list for extendability https://softwareengineering.stackexchange.com/questions/286293/whats-the-best-way-to-return-an-array-as-a-response-in-a-restful-api

```suggestion
    Ok(HttpResponse::Ok().json(json!({ "rooms": rooms })))
```

2021-03-28 18:02 UTC, sirkrypt0 commented on server/src/room/routes.rs
> +}
Not sure if this is required, as `find` already returns the users. Furthermore the JSON that is returned here is simply a list. This should be adjusted imo (see comment on `list`)

2021-03-28 18:02 UTC, sirkrypt0 commented on server/src/room/routes.rs
> +}
Adding a user that does not exist returns `Internal Server Error` here. This is probably an issue in the model. Deleting a user that does not exists returns a proper message.

2021-03-28 18:02 UTC, sirkrypt0 commented on server/src/room/routes.rs
> +}
Adding a user that is already in the room also returns `Internal Server Error`. This is probably an issue in the model as well.

2021-03-30 07:22 UTC, frcroth commented on server/src/room/routes.rs
> +}
Yes find returns the users, but more as a bonus. I felt that since we have post and delete on room/id/users, a get would be nice as well

2021-04-02 15:08 UTC, frcroth commented on server/src/room/routes.rs
> +}
Should be fixed now

2021-04-05 20:08 UTC, sirkrypt0 approved these changes

2021-04-05 20:14 UTC, merged